# -*- coding: utf-8 -*-
"""GFC

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z09JCrOAm2KPrt8w3iBB0dAI5DGfdPyX
"""

import pandas as pd
import matplotlib.pyplot as plt
import re
from matplotlib.patches import Patch
from google.colab import files

uploaded = files.upload()
for filename in uploaded.keys():
    df = pd.read_csv(filename)

df.columns = df.columns.str.strip()

def extrair_serie_pos(texto):
    if pd.isna(texto) or texto == '-':
        return None, None
    match = re.search(r'(Série [A-D])\s*-\s*(\d+)', texto)
    if match:
        return match.group(1), int(match.group(2))
    return None, None

df[['Serie','Posicao']] = df['Liga Nacional'].apply(lambda x: pd.Series(extrair_serie_pos(x)))
anos = df['Ano'].tolist()

plt.figure(figsize=(16,8))
ax = plt.gca()

bases = {'Série A':0, 'Série B':25, 'Série C':50, 'Série D':55}
altura = 20

ax.fill_between([1970.5, max(anos)+0.5], bases['Série A'], bases['Série A']+altura, color='dimgray', alpha=0.8)
ax.fill_between([1970.5, max(anos)+0.5], bases['Série B'], bases['Série B']+altura, color='lightgray', alpha=0.8)
ax.hlines(bases['Série C'], 1981-0.5, max(anos)+0.5, color='lightgray', alpha=0.5, linewidth=4)
ax.hlines(bases['Série D'], 2009-0.5, max(anos)+0.5, color='lightgray', alpha=0.5, linewidth=4)

def cor_posicao(serie, pos):
    if pos == 1:
        return 'gold'
    elif 2 <= pos <= 4:
        return 'darkblue'
    elif serie == 'Série A' and 5 <= pos <= 6:
        return 'lightblue'
    elif serie == 'Série A' and 7 <= pos <= 16:
        return 'white'
    elif serie in ['Série B','Série C','Série D'] and 5 <= pos <= 16:
        return 'white'
    elif pos >= 17:
        return 'red'
    else:
        return 'gray'

x_vals, y_vals = [], []
for idx, row in df.iterrows():
    ano = row['Ano']
    serie = row['Serie']
    pos = row['Posicao']
    if pd.isna(serie) or ano < 1971 or pos > 60:
        continue

    if serie in ['Série A','Série B']:
        base = bases[serie]
        y = base + min(pos, 20)
    elif serie == 'Série C' and ano >= 1981:
        y = bases['Série C']
    elif serie == 'Série D' and ano >= 2009:
        y = bases['Série D']
    else:
        continue

    ax.fill_between([ano-0.5, ano+0.5], y-1, y, color=cor_posicao(serie,pos))
    x_vals.append(ano)
    y_vals.append(y)

ax.step(x_vals, y_vals, where='mid', color='black', linewidth=1.5)

yticks, yticklabels = [], []
for serie in ['Série A','Série B']:
    base = bases[serie]
    for t in [1,5,10,15,20]:
        yticks.append(base + t)
        yticklabels.append(f"{t}º")
ax.set_yticks(yticks)
ax.set_yticklabels(yticklabels)

ax.set_yticks(range(0,61))
ax.grid(axis='y', linestyle='--', color='white', alpha=0.3)
anos_xticks = list(range(1971, max(anos)+1, 5))
ax.set_xticks(anos_xticks)
for ano in anos_xticks:
    ax.vlines(ano, ymin=0, ymax=60, color='gray', alpha=0.2, linestyle='--', linewidth=0.8)

ax.text(1971, bases['Série A']+altura-1, "Série A (1971)", fontsize=12, fontweight='bold', ha='left', va='top', color='black')
ax.text(1971, bases['Série B']+altura-1, "Série B (1971)", fontsize=12, fontweight='bold', ha='left', va='top', color='black')
ax.text(1971, bases['Série C'], "Série C (1981)", fontsize=12, fontweight='bold', ha='left', va='bottom', color='black')
ax.text(1971, bases['Série D'], "Série D (2009)", fontsize=12, fontweight='bold', ha='left', va='bottom', color='black')

ax.set_xlim(1970.5, max(anos)+0.5)
ax.set_ylim(0,60)
ax.invert_yaxis()
ax.set_xlabel("Ano")
ax.set_ylabel("Posição")
ax.set_title("Goiana FC (PE): Histórico no Campeonato Brasileiro (Séries A-D)")

legendas = [
    Patch(facecolor='gold', label='1º lugar'),
    Patch(facecolor='darkblue', label='2º-4º lugar'),
    Patch(facecolor='lightblue', label='5º-6º (Série A)'),
    Patch(facecolor='white', label='7º-16º (Série A) / 5º-16º (B,C,D)'),
    Patch(facecolor='red', label='≥17º')
]
ax.legend(handles=legendas, title='Posições', bbox_to_anchor=(1.02, 1), loc='upper left', borderaxespad=0, frameon=True)

plt.tight_layout()
plt.show()

df.columns = df.columns.str.strip()
anos = df['Ano'].tolist()

def cor_pernambucano(resultado):
    if resultado == 'Campeão':
        return 'gold'
    elif resultado == 'Vice':
        return 'silver'
    elif resultado == '3° lugar':
        return 'blue'
    elif resultado == 'Semifinal':
        return 'dimgray'
    else:
        return 'white'

resultado_counts = df['Campeonato Pernambucano'].value_counts()

fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(16,6), gridspec_kw={'height_ratios':[1,1]})

linha_y = 1.0
altura_quadrado = 0.3
x_vals, y_vals = [], []

for idx, row in df.iterrows():
    ano = row['Ano']
    resultado = row['Campeonato Pernambucano']
    ax1.fill_between([ano-0.5, ano+0.5], linha_y-altura_quadrado/3, linha_y+altura_quadrado/3,
                     color=cor_pernambucano(resultado))

ax1.set_xticks(range(df['Ano'].min(), df['Ano'].max()+1, 5))
ax1.set_yticks([])
ax1.set_xlim(df['Ano'].min()-0.5, df['Ano'].max()+0.5)
ax1.set_ylim(0.5,1.5)
ax1.grid(axis='x', color='white', linestyle='--', alpha=0.7)
ax1.set_title("Goiana FC (PE): Histórico no Campeonato Pernambucano")

ordem = ['Campeão','Vice','3° lugar','Semifinal']
ax2.bar(resultado_counts.index, resultado_counts.values, color=[cor_pernambucano(r) for r in resultado_counts.index])
ax2.set_ylabel("Quantidade de anos")
ax2.set_xlabel("Resultado")
ax2.set_title("Distribuição de resultados no Pernambucano")

legendas = [
    Patch(facecolor='gold', label='Campeão'),
    Patch(facecolor='silver', label='Vice'),
    Patch(facecolor='blue', label='3° lugar'),
    Patch(facecolor='dimgray', label='Semifinal')
]
ax2.legend(handles=legendas, title='Resultados', bbox_to_anchor=(1.02,1), loc='upper left', frameon=True)

plt.tight_layout()
plt.show()

df.columns = df.columns.str.strip()

df_cdb = df[df['Ano'] >= 1988]

fases = ['Não participou','1ª fase','2ª fase','Oitavas','Quartas','Semifinal','Finalista','Campeão']
fase_map = {fase:i for i,fase in enumerate(fases)}
df_cdb['Fase_num'] = df_cdb['Copa do Brasil'].map(fase_map).fillna(0)

cores_map = {
    'Campeão': 'gold',
    'Finalista': 'silver',
    'Semifinal': 'darkblue',
    'Quartas': 'lightblue',
    'Oitavas': 'white',
    '2ª fase': 'dimgray',
    '1ª fase': 'dimgray',
    'Não participou': 'lightgray'
}
y_colors = [cores_map.get(f, 'lightgray') for f in df_cdb['Copa do Brasil']]

plt.figure(figsize=(16,6))
ax = plt.gca()

ax.plot(df_cdb['Ano'], df_cdb['Fase_num'], color='black', linewidth=2)

ax.scatter(df_cdb['Ano'], df_cdb['Fase_num'], color=y_colors, s=100, zorder=5, edgecolor='black')

ax.set_yticks(range(len(fases)))
ax.set_yticklabels(fases)
ax.grid(axis='y', linestyle='--', color='gray', alpha=0.7)

anos_xticks = list(range(1988, df_cdb['Ano'].max()+1, 2))
ax.set_xticks(anos_xticks)
ax.grid(axis='x', linestyle='--', color='gray', alpha=0.3)

ax.set_xlim(1987.5, df_cdb['Ano'].max()+0.5)
ax.set_ylim(-0.5, len(fases)-0.5)
ax.set_xlabel("Ano")
ax.set_ylabel("Fase atingida")
ax.set_title("Goiana FC (PE): Histórico na Copa do Brasil")

from matplotlib.patches import Patch
legendas = [
    Patch(facecolor='gold', label='Campeão'),
    Patch(facecolor='silver', label='Finalista'),
    Patch(facecolor='darkblue', label='Semifinal'),
    Patch(facecolor='lightblue', label='Quartas'),
    Patch(facecolor='white', label='Oitavas'),
    Patch(facecolor='dimgray', label='2ª/1ª fase'),
    Patch(facecolor='lightgray', label='Não participou')
]
ax.legend(handles=legendas, title='Fase atingida', bbox_to_anchor=(1.02,1), loc='upper left', frameon=True)

plt.tight_layout()
plt.show()

df.columns = df.columns.str.strip()

df_cn = df[df['Ano'] >= 1994].copy()

fases = ['1ª fase','Quartas','Semifinal','Vice','Campeão']
fase_map = {fase:i for i,fase in enumerate(fases)}
df_cn['Fase_num'] = df_cn['Copa do Nordeste'].map(fase_map)

anos_sem_disputa = list(range(2004,2010)) + [2011,2012]

cores_map = {
    'Campeão': 'gold',
    'Vice': 'silver',
    'Semifinal': 'darkblue',
    'Quartas': 'lightblue',
    '1ª fase': 'dimgray'
}

plt.figure(figsize=(16,6))
ax = plt.gca()

df_disputados = df_cn[~df_cn['Ano'].isin(anos_sem_disputa)]
df_disputados = df_disputados.sort_values('Ano')

segments_x, segments_y = [], []
prev_ano = None
for idx, row in df_disputados.iterrows():
    ano = row['Ano']
    fase_num = row['Fase_num']
    if prev_ano is None or ano - prev_ano > 1:
        if segments_x:
            ax.plot(segments_x, segments_y, color='black', linewidth=2)
        segments_x = [ano]
        segments_y = [fase_num]
    else:
        segments_x.append(ano)
        segments_y.append(fase_num)
    prev_ano = ano

if segments_x:
    ax.plot(segments_x, segments_y, color='black', linewidth=2)

ax.scatter(df_disputados['Ano'], df_disputados['Fase_num'],
           color=[cores_map[f] for f in df_disputados['Copa do Nordeste']],
           s=100, zorder=5, edgecolor='black')

for ano in anos_sem_disputa:
    ax.hlines(fase_map['1ª fase'], ano-0.4, ano+0.4, color='gray', linewidth=6, alpha=0.9)

ax.set_yticks(range(len(fases)))
ax.set_yticklabels(fases)
ax.grid(axis='y', linestyle='--', color='gray', alpha=0.7)

anos_xticks = list(range(1994, df_cn['Ano'].max()+1, 2))
ax.set_xticks(anos_xticks)
ax.grid(axis='x', linestyle='--', color='gray', alpha=0.3)

ax.set_xlim(1993.5, df_cn['Ano'].max()+0.5)
ax.set_ylim(-0.5, len(fases)-0.5)
ax.set_xlabel("Ano")
ax.set_ylabel("Fase atingida")
ax.set_title("Goiana FC (PE): Histórico na Copa do Nordeste")

legendas = [
    Patch(facecolor='gold', label='Campeão'),
    Patch(facecolor='silver', label='Vice'),
    Patch(facecolor='darkblue', label='Semifinal'),
    Patch(facecolor='lightblue', label='Quartas'),
    Patch(facecolor='dimgray', label='1ª fase'),
    Patch(facecolor='gray', label='Não houve disputa')
]
ax.legend(handles=legendas, title='Fase atingida', bbox_to_anchor=(1.02,1), loc='upper left', frameon=True)

plt.tight_layout()
plt.show()

import re

def extrair_serie_pos(texto):
    if pd.isna(texto) or texto.strip() == '-' or texto.strip() == '':
        return None, None
    match = re.search(r'(Série [A-D])\s*-\s*(\d+)', texto)
    if match:
        return match.group(1), int(match.group(2))
    return None, None

df[['Serie_Liga','Posicao_Liga']] = df['Liga Nacional'].apply(lambda x: pd.Series(extrair_serie_pos(x)))

titulos = {}
for serie in ['Série A','Série B','Série C','Série D']:
    titulos[f'Brasileirão {serie}'] = df[(df['Serie_Liga']==serie) & (df['Posicao_Liga']==1)].shape[0]

titulos['Pernambucano'] = df['Campeonato Pernambucano'].apply(lambda x: 'Campeão' in str(x)).sum()
titulos['Copa do Brasil'] = df['Copa do Brasil'].apply(lambda x: 'Campeão' in str(x)).sum()
titulos['Copa do Nordeste'] = df['Copa do Nordeste'].apply(lambda x: 'Campeão' in str(x)).sum()

labels = [f"{k} ({v})" for k,v in titulos.items()]
sizes = list(titulos.values())
colors = ['gold','lightblue','lightgreen','salmon','orange','violet','cyan']

plt.figure(figsize=(8,8))
wedges, texts = plt.pie(sizes, colors=colors[:len(sizes)], startangle=90, wedgeprops={'edgecolor':'black'})

plt.title("Goiana FC: Títulos por Competição")
plt.legend(wedges, labels, title="Competições", bbox_to_anchor=(1.05, 1), loc="upper left")
plt.tight_layout()
plt.show()

uploaded = files.upload()

filename = list(uploaded.keys())[0]
df = pd.read_csv(filename)

df = df.drop_duplicates(subset='Nome')

top10 = df.nlargest(10, 'Partidas').sort_values('Partidas', ascending=True)

colors = ['#4c72b0','#55a868','#c44e52','#8172b3','#ccb974',
          '#64b5cd','#8c564b','#e377c2','#7f7f7f','#bcbd22']

plt.figure(figsize=(14,7))
bars = plt.barh(top10['Nome'], top10['Partidas'], color=colors, edgecolor='black')

for bar in bars:
    width = bar.get_width()
    plt.text(width + 2, bar.get_y() + bar.get_height()/2, str(width),
             va='center', fontsize=10, fontweight='bold', color='black')

plt.xlabel('Número de Partidas', fontsize=12, fontweight='bold')
plt.title('Top 10 Jogadores com Mais Jogos', fontsize=14, fontweight='bold')
plt.grid(axis='x', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

df.columns = df.columns.str.strip().str.replace('ç','c').str.replace('ã','a').str.replace('ê','e')

df = df.drop_duplicates(subset='Nome')

def plot_top10(df, coluna, titulo):
    if coluna not in df.columns:
        print(f"Coluna '{coluna}' não encontrada!")
        return
    top10 = df.nlargest(10, coluna).sort_values(coluna, ascending=False)
    colors = ['#4c72b0','#55a868','#c44e52','#8172b3','#ccb974',
              '#64b5cd','#8c564b','#e377c2','#7f7f7f','#bcbd22']

    plt.figure(figsize=(14,7))
    bars = plt.bar(top10['Nome'], top10[coluna], color=colors, edgecolor='black')

    for bar in bars:
        height = bar.get_height()
        plt.text(bar.get_x() + bar.get_width()/2, height + 0.5, str(height),
                 ha='center', va='bottom', fontsize=10, fontweight='bold', color='black')

    plt.ylabel(coluna, fontsize=12, fontweight='bold')
    plt.xlabel('Jogadores', fontsize=12, fontweight='bold')
    plt.title(titulo, fontsize=14, fontweight='bold')
    plt.xticks(rotation=45, ha='right')
    plt.grid(axis='y', linestyle='--', alpha=0.5)
    plt.tight_layout()
    plt.show()

plot_top10(df, 'Partidas', 'Top 10 Jogadores com Mais Jogos')
plot_top10(df, 'Gols', 'Top 10 Jogadores com Mais Gols')
plot_top10(df, 'Assistencias', 'Top 10 Jogadores com Mais Assistencias')

df.columns = df.columns.str.strip().str.replace('ç','c').str.replace('ã','a').str.replace('é','e')
df = df.drop_duplicates(subset='Nome')

df['Media_Gols'] = df['Gols'] / df['Partidas']

top10_media = df.nlargest(10, 'Media_Gols').sort_values('Media_Gols', ascending=False)

colors = ['#4c72b0','#55a868','#c44e52','#8172b3','#ccb974',
          '#64b5cd','#8c564b','#e377c2','#7f7f7f','#bcbd22']

plt.figure(figsize=(14,7))
bars = plt.bar(top10_media['Nome'], top10_media['Media_Gols'], color=colors, edgecolor='black')

for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, height + 0.01, f"{height:.2f}",
             ha='center', va='bottom', fontsize=10, fontweight='bold', color='black')

plt.ylabel('Média de Gols por Jogo', fontsize=12, fontweight='bold')
plt.xlabel('Jogadores', fontsize=12, fontweight='bold')
plt.title('Top 10 Jogadores por Média de Gols por Jogo', fontsize=14, fontweight='bold')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

df.columns = df.columns.str.strip().str.replace('ç','c').str.replace('ã','a').str.replace('é','e')
df = df.drop_duplicates(subset='Nome')

df['Assist_por_jogo'] = df['Assistencias'] / df['Partidas']

top10_assist_jogo = df.nlargest(10, 'Assist_por_jogo').sort_values('Assist_por_jogo', ascending=True)

colors = ['#4c72b0','#55a868','#c44e52','#8172b3','#ccb974',
          '#64b5cd','#8c564b','#e377c2','#7f7f7f','#bcbd22']

plt.figure(figsize=(14,7))
bars = plt.barh(top10_assist_jogo['Nome'], top10_assist_jogo['Assist_por_jogo'], color=colors, edgecolor='black')

for bar in bars:
    width = bar.get_width()
    plt.text(width + 0.01, bar.get_y() + bar.get_height()/2, f"{width:.2f}",
             ha='left', va='center', fontsize=10, fontweight='bold', color='black')

plt.xlabel('Média de Assistências por Jogo', fontsize=12, fontweight='bold')
plt.ylabel('Jogadores', fontsize=12, fontweight='bold')
plt.title('Top 10 Jogadores por Média de Assistências por Jogo', fontsize=14, fontweight='bold')
plt.grid(axis='x', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

import re

# Função para extrair série e posição
def extrair_serie_pos(texto):
    if pd.isna(texto) or texto.strip() == '-' or texto.strip() == '':
        return None, None
    match = re.search(r'(Série [A-D])\s*-\s*(\d+)', texto)
    if match:
        return match.group(1), int(match.group(2))
    return None, None

# Criar colunas Serie_Liga e Posicao_Liga
df[['Serie_Liga','Posicao_Liga']] = df['Liga Nacional'].apply(lambda x: pd.Series(extrair_serie_pos(x)))

# Agora podemos contar apenas os vices
vices = {}

# Brasileirão por série
for serie in ['Série A','Série B','Série C','Série D']:
    vices[f'Brasileirão {serie} 2º'] = df[(df['Serie_Liga']==serie) & (df['Posicao_Liga']==2)].shape[0]

# Pernambucano
vices['Pernambucano Vice'] = df['Campeonato Pernambucano'].apply(lambda x: 'Vice' in str(x)).sum()

# Copa do Brasil
vices['Copa do Brasil Finalista'] = df['Copa do Brasil'].apply(lambda x: 'Finalista' in str(x)).sum()

# Copa do Nordeste
vices['Copa do Nordeste Vice'] = df['Copa do Nordeste'].apply(lambda x: 'Vice' in str(x)).sum()

# Gráfico de pizza
import matplotlib.pyplot as plt

labels = [f"{k} ({v})" for k,v in vices.items() if v>0]
sizes = [v for v in vices.values() if v>0]

colors = ['lightblue','lightgreen','salmon','violet']  # cores personalizadas para vices

plt.figure(figsize=(8,8))
wedges, texts = plt.pie(sizes, colors=colors[:len(sizes)], startangle=90, wedgeprops={'edgecolor':'black'})

plt.title("Goiana FC: Vices por Competição")
plt.legend(wedges, labels, title="Competições", bbox_to_anchor=(1.05, 1), loc="upper left")
plt.tight_layout()
plt.show()