# -*- coding: utf-8 -*-
"""Thomaz Lima - Aula 09 - AVD - Análise descritiva de dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KlAiDt9VkYLmJrxjLD9dsJiqnnoGAQRx

# Investigação: O Mistério do Turnover

Você acaba de ser contratado como **analista de dados**.  
A diretoria de Recursos Humanos está preocupada: **muitos funcionários têm deixado a organização** nos últimos anos, e ainda não se sabe bem o porquê.  

Seu desafio é **explorar os dados de RH da empresa** e descobrir padrões escondidos que ajudem a responder perguntas como:  
- Quem está saindo mais da empresa?  
- Os salários estão bem distribuídos?  
- A força de trabalho é jovem ou madura?  
- Existe desigualdade entre departamentos ou cargos?  
- A satisfação no trabalho está ligada ao turnover?

## O Dataset

O conjunto de dados que vamos usar é o **IBM HR Analytics Employee Attrition & Performance**.  
Ele contém informações de **~1.500 funcionários**, com variáveis relacionadas a:  

- **Perfil do funcionário**  
  - `Age`: idade  
  - `Gender`: gênero  
  - `EducationField`: área de formação  
  - `DistanceFromHome`: distância de casa até a empresa  

- **Trabalho e carreira**  
  - `Department`: departamento  
  - `JobRole`: cargo  
  - `MonthlyIncome`: salário mensal  
  - `YearsAtCompany`: tempo de empresa  

- **Satisfação e retenção**  
  - `JobSatisfaction`: nível de satisfação (escala 1 a 4)  
  - `Attrition`: se o funcionário deixou a empresa (Sim/Não)

  O dataset será carregado a seguir.
"""

import kagglehub
import matplotlib.pyplot as plt
import pandas as pd

path = kagglehub.dataset_download("pavansubhasht/ibm-hr-analytics-attrition-dataset")
df = pd.read_csv(path + "/WA_Fn-UseC_-HR-Employee-Attrition.csv")

"""## Objetivo da Atividade

Você e sua equipe vão atuar como **detetives de dados**.  
Receberão **missões de investigação**, cada uma focada em um aspecto do dataset.  
Para resolvê-las, será necessário:  

- Calcular medidas descritivas (média, mediana, desvio padrão).  
- Montar tabelas de frequência.  
- Produzir gráficos que ajudem na interpretação ([façam o uso das boas práticas discutidas em aula](https://docs.google.com/presentation/d/187XSKM0-gI0VaBb1uIkWyRQ_LPcacdd4/edit?usp=sharing&ouid=109823011426401521036&rtpof=true&sd=true)).  
- Responder às **perguntas motivadoras** com base nos resultados.  

No final, cada grupo deverá apresentar:  
1. **Um insight** (o que descobriram).  
2. **Uma recomendação prática** para o RH da empresa.

## Missão 1 - O salário típico

**O que fazer:**
Calcule a **média** e a **mediana** de `MonthlyIncome`. Compare os valores.  

**Pergunta motivadora:**  
Qual medida representa melhor o salário típico da empresa?  

**Gráfico sugerido:**  
Histograma ou boxplot dos salários.
"""

df_boxplot = df.dropna(subset=['MonthlyIncome', 'Attrition'])
dados_y = df_boxplot[df_boxplot['Attrition'] == 'Yes']['MonthlyIncome']
dados_n = df_boxplot[df_boxplot['Attrition'] == 'No']['MonthlyIncome']

plt.figure(figsize=(12,6))

b = plt.boxplot([dados_n, dados_y],
                labels=['Empregado', 'Não Empregado'],
                patch_artist=True,
                medianprops=dict(color='red', linewidth=2),
                boxprops=dict(linewidth=1.5),
                whiskerprops=dict(linewidth=1.5),
                capprops=dict(linewidth=1.5))

colors = ['#1f77b4', '#ff7f0e']
for patch, color in zip(b['boxes'], colors):
    patch.set_facecolor(color)
    patch.set_edgecolor('white')

plt.title('Distribuição dos Salários por Situação na Empresa', fontsize=16, pad=15, weight='bold')
plt.ylabel('Salário (R$)', fontsize=13, weight='bold')

plt.grid(axis='y', linestyle='--', alpha=0.6)

plt.tight_layout()
plt.show()

"""Com o gráfico, podemos observar que as pessoas que estavam empregadas durante a pesquisa, possuíam salários maiores, tanto em média, mediana e em valóres máximos e mínimos. Essa discrepância pode ser atribuida a vários fatores, como uma redistribuição dos salários após as demissões, maiores demissões em departamentos que receberiam menores salários ou saída dos funcionários que receberam menos salários. Podemos também observar uma grande quantidade de outliers nos empregados, que podem ser atribuídos a casos como comissões recebidas pelo setor de vendas ou maiores salários para cargos de liderança e de maior senioridade.

## Missão 2 - Desigualdade entre departamentos
**O que fazer:**  
Calcule a **média** e o **desvio padrão** de `MonthlyIncome` por `Department`.  

**Pergunta motivadora:**  
Alguns departamentos são mais desiguais internamente? Isso é um problema ou esperado?  

**Gráfico sugerido:**  
Boxplot comparando salários por departamento.
"""

income_per_department_mean_std = df.groupby('Department')['MonthlyIncome'].agg(['mean', 'std'])

df_boxplot = df.dropna(subset=['MonthlyIncome', 'Department'])
dados_hr = df_boxplot[df_boxplot['Department'] == 'Human Resources']['MonthlyIncome']
dados_rd = df_boxplot[df_boxplot['Department'] == 'Research & Development']['MonthlyIncome']
dados_sales = df_boxplot[df_boxplot['Department'] == 'Sales']['MonthlyIncome']

plt.figure(figsize=(12,6))

b = plt.boxplot([dados_hr, dados_rd, dados_sales],
                labels=['Human Resources', 'R&D', 'Sales'],
                patch_artist=True,
                medianprops=dict(color='red', linewidth=2),
                boxprops=dict(linewidth=1.5),
                whiskerprops=dict(linewidth=1.5),
                capprops=dict(linewidth=1.5))

cores = ['#1f77b4', '#ff7f0e', '#2ca02c']
for patch, color in zip(b['boxes'], cores):
    patch.set_facecolor(color)
    patch.set_edgecolor('white')

plt.title('Distribuição dos Salários por Departamento', fontsize=16, pad=15, weight='bold')
plt.ylabel('Salário (R$)', fontsize=13, weight='bold')

plt.grid(axis='y', linestyle='--', alpha=0.6)

plt.tight_layout()
plt.show()

"""Podemos observar, que, de forma geral o departamento que tem a menor remuneração é o de RH. Também é visível que o departamento de Pesquisa e desenvolvimento apresenta vários outlayers positivos, sendo, destacadamente, o com o maior número dentre os 3 departamentos. Por fim, uma análise mais precisa da remuneração média clama por uma análise desensiderando, total ou parcialmente, os Outlayers.

## Missão 3 – A idade dos funcionários
**O que fazer:**  
Monte uma tabela de frequência por faixas etárias (`Age`).  

**Pergunta motivadora:**  
A força de trabalho é predominantemente jovem ou madura? Como isso impacta políticas de RH?  

**Gráfico sugerido:**  
Histograma ou gráfico de barras das faixas etárias.
"""

bins = [0, 19, 29, 39, 49, 59, 69]
labels = ['<20', '20-29', '30-39', '40-49', '50-59', '60+']

df['Faixa Etária'] = pd.cut(df['Age'], bins=bins, labels=labels, right=True)

tabela_freq = df['Faixa Etária'].value_counts().sort_index().reset_index()
tabela_freq.columns = ['Faixa Etária', 'Frequência']
tabela_freq['Frequência Relativa (%)'] = (tabela_freq['Frequência'] / tabela_freq['Frequência'].sum()) * 100

cores = plt.cm.viridis(range(len(tabela_freq)))

plt.figure(figsize=(9,6))
barras = plt.bar(tabela_freq['Faixa Etária'], tabela_freq['Frequência'],
                 color=cores, edgecolor='white', linewidth=1.2)

plt.title("Distribuição por Faixas Etárias - Funcionários", fontsize=16, pad=15, weight='bold')
plt.xlabel("Faixa Etária", fontsize=13)
plt.ylabel("Número de Funcionários", fontsize=13)

plt.grid(axis='y', linestyle='--', alpha=0.6)

for barra in barras:
    altura = barra.get_height()
    plt.text(barra.get_x() + barra.get_width()/2, altura + 5,
             f"{int(altura)}", ha='center', fontsize=11, weight='bold', color="#333")

plt.box(False)

plt.show()

"""Ao analisar o gráfico, fica evidente que o perfil dos funcionários da IBM é marcado por focar bastante na experiência. A maior parte se encontra no que costuma ser chamado de “auge da carreira empresarial”, faixa que vai dos 30 aos 50 anos, visto que, são profissionais com muita bagagem e em plena capacidade de entrega para a empresa. Outro ponto que chama atenção é o número baixíssimo de jovens: em um universo de 1500 funcionários, apenas 17 têm menos de 20 anos, o que representa pouco mais de 1%. Já o grupo acima dos 60 anos, mesmo com o etarismo na área, não surpreende, considerando que 55% das cadeiras de diretoria em empresas de tecnologia são ocupadas justamente por profissionais dessa faixa etária.

## Missão 4 – Formação educacional
**O que fazer:**  
Monte uma tabela de frequência para `EducationField`.  

**Pergunta motivadora:**  
O mix de formações é diversificado ou concentrado? Isso traz riscos ou oportunidades?  

**Gráfico sugerido:**  
Gráfico de barras ou pizza da distribuição de formações.
"""

tabela_edu = df['EducationField'].value_counts().reset_index()
tabela_edu.columns = ['Área de Formação', 'Frequência']
tabela_edu['Frequência Relativa (%)'] = (tabela_edu['Frequência'] / tabela_edu['Frequência'].sum()) * 100

cores = plt.cm.Paired(range(len(tabela_edu)))

plt.figure(figsize=(9,6))
barras = plt.bar(tabela_edu['Área de Formação'], tabela_edu['Frequência'],
                 color=cores, edgecolor='white', linewidth=1.2)

plt.title("Distribuição das Áreas de Formação", fontsize=16, pad=15, weight='bold')
plt.xlabel("Área de Formação", fontsize=13)
plt.ylabel("Número de Funcionários", fontsize=13)
plt.xticks(rotation=30, ha='right')

plt.grid(axis='y', linestyle='--', alpha=0.6)

for barra in barras:
    altura = barra.get_height()
    plt.text(barra.get_x() + barra.get_width()/2, altura + 5,
             f"{int(altura)}", ha='center', fontsize=11, weight='bold', color="#333")

plt.box(False)
plt.show()

"""Observando o gráfico, salta aos olhos a forte presença de profissionais de Life Sciences, área ligada à pesquisa e ao desenvolvimento de soluções voltadas para a vida humana. A medicina também aparece em destaque, o que faz sentido por estar intimamente conectada às ciências da natureza. No entanto, o ponto central é a enorme concentração em nas duas áreas que juntas,representam mais de dois terços de todo o quadro da empresa, muito à frente do departamento de Marketing, o único que chega perto em números. Do ponto de vista empresarial, essa escolha é no mínimo questionável, já que a diversidade de perspectivas fica comprometida, ainda mais quando pensamos que são áreas que, em linhas gerais, pouco dialogam entre si.

## Missão 5 – Turnover global

O que fazer:**  
Calcule a **frequência relativa** de `Attrition` (Sim/Não).  

**Pergunta motivadora:**  
Essa taxa de saída deve ser considerada preocupante? Por quê?  

**Gráfico sugerido:**  
Gráfico de pizza ou barras simples (saiu vs ficou).
"""

attrition_counts = df['Attrition'].value_counts(normalize=True) * 100
cores = ['#1f77b4', '#ff7f0e']

plt.figure(figsize=(6,6))
wedges, texts, autotexts = plt.pie(
    attrition_counts,
    labels=attrition_counts.index,
    autopct='%1.1f%%',
    startangle=90,
    colors=cores,
    wedgeprops={'edgecolor':'white', 'linewidth':1.2},
    textprops={'fontsize':12, 'weight':'bold', 'color':'white'}
)

plt.title('Distribuição de Turnover', fontsize=16, pad=15, weight='bold')

plt.show()

"""Baseado nos resultados, a frequência relativa de turnover é de aproximadamente **16.1%**. Considerar essa taxa preocupante depende do contexto da empresa e do setor. Em muitos setores, 16.1% seria considerado uma taxa moderada a alta, o que pode indicar custos elevados com rotatividade, como recrutamento e treinamento. No entanto, é essencial comparar essa taxa com benchmarks do setor e investigar as razões por trás das saídas (que serão exploradas nas próximas missões) para uma avaliação mais precisa.

## Missão 6 – Distância da empresa
**O que fazer:**  
Agrupe `DistanceFromHome` em classes (0–5, 6–10, 11–20, 21+ km) e calcule a frequência.  

**Pergunta motivadora:**  
Morar mais longe influencia retenção? Que políticas poderiam ajudar?  

**Gráfico sugerido:**  
Histograma ou gráfico de barras com classes de distância.
"""

distance_bins = [0, 5, 10, 20, df['DistanceFromHome'].max()]
distance_labels = ['0-5 km', '6-10 km', '11-20 km', '21+ km']
df['DistanceGroup'] = pd.cut(df['DistanceFromHome'], bins=distance_bins, labels=distance_labels, right=False)

distance_counts = df['DistanceGroup'].value_counts(normalize=True) * 100

plt.figure(figsize=(8,6))
cores = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728']  # cores diferentes para cada faixa
barras = plt.bar(distance_counts.index, distance_counts.values, color=cores, edgecolor='white', linewidth=1.2)

plt.title('Distribuição de Funcionários por Distância de Casa', fontsize=16, pad=15, weight='bold')
plt.xlabel('Distância de Casa (km)', fontsize=13, weight='bold')
plt.ylabel('Frequência Relativa (%)', fontsize=13, weight='bold')
plt.ylim(0, distance_counts.max() + 5)

for i, val in enumerate(distance_counts.values):
    plt.text(i, val + 0.5, f"{val:.1f}%", ha='center', fontsize=11, weight='bold', color='#333')

plt.grid(axis='y', linestyle='--', alpha=0.6)

plt.box(False)

plt.xticks(rotation=45, ha='right', fontsize=11)
plt.tight_layout()
plt.show()

"""Para poder responder se morar mais longe influencia a retenção, seria necessário analisar a taxa de turnover dentro de cada uma dessas faixas de distância. Se as faixas de maior distância apresentarem taxas de turnover significativamente maiores, isso sugere que a distância pode ser um fator contribuinte para a saída de funcionários. Sem isso, estaríamos apenas especulando em cima de dados qeu podem não ter nenhuma relação.

## Missão 7 – Turnover por gênero
**O que fazer:**  
Monte uma tabela cruzada entre `Attrition` e `Gender`.  

**Pergunta motivadora:**  
Homens e mulheres apresentam taxas de saída diferentes? Como interpretar?  

**Gráfico sugerido:**  
Gráfico de barras agrupadas (masculino vs feminino, permaneceu vs saiu).
"""

contagem = pd.crosstab(df['Gender'], df['Attrition'], normalize='index') * 100

cores = ['#1f77b4', '#ff7f0e']

ax = contagem.plot(kind='bar', stacked=True, figsize=(9,6), color=cores, edgecolor='white', linewidth=1.2)

plt.title("Saída da Empresa por Gênero (%)", fontsize=16, pad=15, weight='bold')
plt.xlabel("Gênero", fontsize=13)
plt.ylabel("Percentual (%)", fontsize=13)
plt.xticks(rotation=0)

for container in ax.containers:
    ax.bar_label(container, fmt="%.1f%%", label_type='center', fontsize=10, weight='bold', color="white")

plt.grid(axis='y', linestyle='--', alpha=0.6)

plt.legend(title='Saída')

plt.box(False)

plt.show()

"""O gráfico apresenta a contagem de funcionários por gênero e sua situação em relação à saída da empresa. A barra azul representa os funcionários que permaneceram na empresa, enquanto a barra laranja indica aqueles que saíram.


Ademais, é possível observar que, mesmo que as mulheres saiam menos da empresa, o percentil é, ainda bastante parecido, e não representa um comportamento significativamente diferente entre os gêneros.

## Missão 8 – Turnover por departamento
**O que fazer:**  
Monte uma tabela cruzada entre `Attrition` e `Department`.  

**Pergunta motivadora:**  
Qual departamento apresenta maior risco de saída? O que poderia explicar isso?  

**Gráfico sugerido:**  
Gráfico de barras horizontais comparando taxa de saída por departamento.
"""

contagem = pd.crosstab(df['Department'], df['Attrition'])

percentuais = contagem.div(contagem.sum(axis=1), axis=0) * 100

cores = ['#1f77b4', '#ff7f0e']

ax = percentuais.plot(kind='barh', stacked=True, figsize=(10, 6),
                      color=cores, edgecolor='white', linewidth=1.2)

plt.title('Saída da Empresa por Department (%)', fontsize=16, pad=15, weight='bold')
plt.xlabel('Percentual (%)', fontsize=13)
plt.ylabel('Departamento', fontsize=13)

plt.grid(axis='x', linestyle='--', alpha=0.6)

for i, (index, row) in enumerate(percentuais.iterrows()):
    acumulado = 0
    for attrition, valor in row.items():
        if valor > 0:
            plt.text(acumulado + valor / 2, i, f'{valor:.1f}%',
                     va='center', ha='center', fontsize=10, weight='bold', color='white')
            acumulado += valor

plt.legend(title='Saída', bbox_to_anchor=(1.05, 1), loc='upper left')

plt.tight_layout()
plt.box(False)

plt.show()

"""Originalmente, foi elaborado um gráfico que mostrava a contagem de pessoas que saíram ou permaneceram na empresa por departamento. Embora o gráfico revelasse que a taxa de saída era baixa em todos os departamentos, a comparação entre eles era dificultada pela grande diferença no tamanho das equipes, visto que, o departamento de Pesquisa e Desenvolvimento possui cerca de 800 funcionários, enquanto Recursos Humanos tem menos de 100.


Por isso, o gráfico foi atualizado para apresentar a proporção de saída em vez da contagem absoluta, o que permitiu uma análise mais justa entre os departamentos.


Com essa nova visualização, observamos que, apesar de Pesquisa e Desenvolvimento ser o maior departamento da empresa, ele apresenta proporcionalmente uma das menores taxas de saída. Em contraste, Recursos Humanos, embora tenha o menor número de funcionários, possui a maior taxa de saída proporcional.

## Missão 9 – Salário por cargo
**O que fazer:**  
Calcule a **média** e o **desvio padrão** de `MonthlyIncome` por `JobRole`.  

**Pergunta motivadora:**  
Alguns cargos apresentam maior desigualdade salarial? Isso é esperado ou problemático?  

**Gráfico sugerido:**  
Boxplot de salários por cargo.
"""

import seaborn as sns

limite_superior = 16000

plt.figure(figsize=(12,6))
sns.set_style("whitegrid")

paleta = sns.color_palette("Set2", df['JobRole'].nunique())

sns.boxplot(x="JobRole", y="MonthlyIncome", data=df[df['MonthlyIncome'] <= limite_superior], palette=paleta)

plt.ylim(0, limite_superior)
plt.yticks(np.arange(0, limite_superior+1, 2000))

plt.xticks(rotation=45, ha='right', fontsize=11)
plt.xlabel("Cargo", fontsize=13, weight='bold')
plt.ylabel("Salário Mensal ($)", fontsize=13, weight='bold')

plt.title("Distribuição de Salário Mensal por Cargo (foco na maior parte dos dados)", fontsize=16, pad=15, weight='bold')

plt.grid(axis='y', linestyle='--', alpha=0.6)

sns.despine(trim=True)

plt.tight_layout()
plt.show()

"""Ao analisar o gráfico, é notória a grande diferença de remuneração entre as diferentes funções na empresa. Cargos como o de gerente apresentam uma remuneração média extremamente alta, por outro lado, quando vamos para os representantes de vendas, seus slários são bem mais baixos, além de apresentarem inúmeros outlayers, o que, de certo modo, é normal para um cargo que recebe pro comissão.

## Missão 10 - Satisfação por departamento
**O que fazer:**  
Calcule a **média** de `JobSatisfaction` por `Department`.  

**Pergunta motivadora:**  
Existe algum departamento com nível de satisfação significativamente menor? Que ação poderia ser tomada?  

**Gráfico sugerido:**  
Gráfico de barras com satisfação média por departamento.
"""

department_satisfaction = round(df.groupby("Department").JobSatisfaction.mean(), 2)

plt.figure(figsize=(8,5))
sns.set_style("whitegrid")

paleta = sns.color_palette("Set2", df['Department'].nunique())
ax = sns.barplot(x="Department", y="JobSatisfaction", data=df, palette=paleta, ci=None, edgecolor='white')

plt.title("Satisfação Média por Departamento", fontsize=16, pad=15, weight='bold')
plt.xlabel("Departamento", fontsize=13, weight='bold')
plt.ylabel("Satisfação Média", fontsize=13, weight='bold')
plt.ylim(0, 4)

plt.grid(axis='y', linestyle='--', alpha=0.6)

for p in ax.patches:
    altura = p.get_height()
    ax.text(p.get_x() + p.get_width()/2, altura + 0.05, f"{altura:.2f}",
            ha='center', fontsize=11, weight='bold', color='#333')

plt.xticks(rotation=30, ha='right', fontsize=11)

sns.despine(trim=True)

plt.tight_layout()
plt.show()

"""O departamento de Human Resources (RH) apresentou a menor média de satisfação (2.60), ainda assim, ainda é considerávelmente baixa.

Coisas como, sobrecarga de trabalho sem reconhecimento e sentimento de isolamento (RH costuma apoiar os outros, mas recebe pouco suporte) podem explicar essa questão. Algumas ações recomendadas são: Realizar uma pesquisa interna mais detalhada, com perguntas qualitativas e quantitativas, para entender a origem da insatisfação, entrevistas confidenciais com membros do RH para entender dores e sugestões, e revisar políticas de reconhecimento e valorização interna.

# O que descobriram e qual a recomendação prática para o RH da empresa?

A análise revelou que a empresa possui um perfil de funcionários concentrado na faixa dos 30 a 50 anos, com pouca diversidade de áreas e baixa presença de jovens. A taxa de turnover está em torno de 16,1%, sendo maior no departamento de RH, que também apresenta a menor satisfação dos funcionários, possivelmente devido à sobrecarga e falta de reconhecimento. Além disso, mulheres têm maior retenção que homens, e a distância da residência pode influenciar a saída dos colaboradores.
Para o RH, a recomendação é diversificar o perfil dos funcionários, atraindo jovens e profissionais de outras áreas, além de investigar as causas do turnover, especialmente no próprio RH, e desenvolver políticas de retenção, como maior suporte e reconhecimento. Também é importante revisar as políticas salariais para garantir justiça e transparência, e investir no bem-estar e desenvolvimento da equipe de RH para reduzir a insatisfação e a rotatividade.
"""