# -*- coding: utf-8 -*-
"""Thomaz Lima- Aula 07 - AVD - Tipos de gráficos II.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_wtMoj_NSApDLSVz0jyl4GZVcSfe65aX

# Pergunta fundamental
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](
https://colab.research.google.com/github/<usuario>/<repo>/blob/<branch>/<caminho>/notebook.ipynb
)

Como podemos visualizar a forma como nossos dados se espalham e se conectam, tanto numericamente quanto no espaço?"
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(14, 5))
sns.set_theme(style="whitegrid")
penguins = sns.load_dataset("penguins")
penguins.head()

"""## Exercício

1. **Analisar a relação entre Nadadeiras e Massa Corporal**: Crie um gráfico de dispersão (scatterplot) que mostre a relação entre o comprimento da nadadeira (flipper_length_mm) no eixo X e a massa corporal (body_mass_g) no eixo Y.
   1. **Responda**: Que tipo de correlação você observa? É forte ou fraca? Positiva ou negativa?

2. **Análise por Espécie**: Pegue o gráfico anterior e adicione a variável species como um parâmetro de cor (hue).

    1. **Responda**: O padrão de correlação que você observou antes se mantém para todas as espécies? A espécie Gentoo (verde) continua se destacando das demais? Como?

3. **Comparando Bicos por Ilha**. Use um box plot (boxplot) para comparar a distribuição do comprimento do bico (bill_length_mm) entre as três ilhas (island).
    1. **Responda**: Existe alguma diferença visível na distribuição do comprimento do bico dependendo da ilha? Qual ilha parece ter os pinguins com bicos mais longos em média?

## 1°
"""

plt.figure(figsize=(14, 5))
sns.scatterplot(data=penguins, x="flipper_length_mm", y="body_mass_g")

plt.title('Relação entre Tamanho das Nadadeiras e Massa Corporal dos Pinguins')
plt.xlabel('Tamanho das Nadadeiras')
plt.ylabel('Massa Coporal')
plt.show()

"""Com base na análise preliminar do gráfico, é possível identificar uma forte correlação positiva entre o comprimento das nadadeiras e a massa corporal dos pinguins.

## 2°
"""

plt.figure(figsize=(14, 5))
sns.scatterplot(data=penguins, x="flipper_length_mm", y="body_mass_g", hue="species")

plt.title('Relação entre Tamanho das Nadadeiras e Massa Corporal dos Pinguins')
plt.xlabel('Tamanho das Nadadeiras')
plt.ylabel('Massa Coporal')
plt.legend(title='Espécie')
plt.show()

"""Observa-se que os pinguins Adelie e Chinstrap não apresentam diferenças significativas entre si. Em contraste, os pinguins Gentoo se destacam por um comportamento distinto em relação aos demais grupos, sendo mais pesados e possuindo nadadeiras maiores.

## 3°
"""

plt.figure(figsize=(14, 5))
sns.boxplot(data=penguins, x="island", y="bill_length_mm")

plt.title('Comparação do Comprimento do Bico por ilha')
plt.xlabel('Espécie')
plt.ylabel('Comprimento da Nadadeira (mm)')

plt.show()

"""É evidente que os pinguins da ilha Torgersen apresentam, de forma destacada, o menor comprimento de nadadeira, além de exibirem a menor variação interna entre os indivíduos. Já os da ilha Dream não possuem a maior média, mas se diferenciam por apresentarem a maior dispersão. Por fim, os pinguins da ilha Biscoe registram a maior média, embora esse resultado possa estar influenciado por um outlier notório, visto que a diferença em relação à ilha Dream não é tão expressiva.

## Exercício

1. Crie um mapa de bolhas (px.scatter_geo) usando os dados de 2007. Configure os seguintes parâmetros:

   * locations = "iso_alpha"
   * size = "gdpPercap" (PIB per capita)
   * color = "continent"
   * hover_name = "country"
   * title = "PIB per Capita no Mundo em 2007"

    1. Quais continentes concentram os países com maior PIB per capita (bolhas maiores)?
    2. No mapa da aula, a China e a Índia tinham bolhas gigantes por causa de suas populações. Como elas aparecem neste mapa de PIB per capita? O que essa diferença de visualização nos ensina?
"""

import plotly.express as px

gapminder = px.data.gapminder()

gapminder_2007 = gapminder.query("year == 2007")

fig = px.scatter_geo(gapminder_2007,
                     locations="iso_alpha",
                     size="gdpPercap",
                     hover_name="country",
                     color="continent",
                     title="PIB per Capita por País em 2007",
                     projection="natural earth")
fig.show()

"""Ao observar o mapa de bolhas, fica claro que os maiores valores se concentram principalmente na Europa Ocidental, com destaque para países como França, Alemanha, Irlanda e também outros da região como Noruega e Suíça. Além da Europa, os Estados Unidos e o Canadá na América do Norte também aparecem com bolhas grandes, assim como Austrália e Nova Zelândia na Oceania e alguns países do Oriente Médio, como Kuwait e Israel. Já a China e a Índia, que no mapa baseado em população tinham bolhas gigantes, agora aparecem com bolhas pequenas, mostrando que, apesar de serem potências populacionais, o PIB dividido pelo tamanho da população resulta em valores médios muito menores. Essa diferença apenas mostra que analisar população e PIB per capita traz perspectivas distintas: enquanto o primeiro mostra o peso demográfico de um país, o segundo evidencia a prosperidade média de seus cidadãos, revelando que ter muita gente não significa, necessariamente, ter maior qualidade de vida.

## Referências

*   Gorman KB, Williams TD, Fraser WR (2014). Ecological sexual
dimorphism and environmental variability within a community of Antarctic penguins (genus Pygoscelis). PLoS ONE 9(3):e90081. https://doi.org/10.1371/journal.pone.0090081
"""